### ISSUE TITLE
大澤 昂太さんのセッション英語タイトル修正

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2023.scalamatsuri.org#135]
[タイムテーブル(英)](https://scalamatsuri.org/en/program/)のDAY2 4/16 12:00 大澤 昂太さんのセッションタイトルについて
「Current state of products made with DDD & Scala.」へ変更をお願いします。

**Comment by ik11235** [comment]
PR: https://github.com/scalamatsuri/2023.scalamatsuri.org/pull/136

**Comment by tomoco95** [comment]
対応ありがとうございました！
