### ISSUE TITLE
岩井雄一郎さんのセッション英語タイトル修正

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2023.scalamatsuri.org#148]
[タイムテーブル(英)](https://scalamatsuri.org/en/program/)のDAY1 4/15 11:15 岩井雄一郎さんのセッションタイトルについて
「Introduction to Functional Programming through CSV
Import」へ変更をお願いします。

**Comment by omiend** [comment]
https://github.com/scalamatsuri/2023.scalamatsuri.org/pull/149
