### ISSUE TITLE
OPG画像を作成する

### ISSUE THREAD

**Issue by omiend** [scalamatsuri/2023.scalamatsuri.org#2]
↓にあるファイルから 2023年版の OGP 画像を作成し、WEBサイトに適用したい
https://drive.google.com/drive/folders/1bt4eSoumzZFVvJrozT9cWfSrOTO6pnb0

**Comment by tomoco95** [comment]
2023年版のOPG画像を作成しました
https://drive.google.com/drive/folders/1XJ5B73USg6lekOBRiKEUX6S3yeDfYlOp?usp=sharing

**Comment by omiend** [comment]
差し替えましたー！Done！
