### ISSUE TITLE
Webロゴ掲載(株式会社はてな様)

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2023.scalamatsuri.org#31]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する
template:
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: "https://hatena.co.jp/recruit/engineer”

ロゴ画像:https://hatena.co.jp/recruit/engineer

**Comment by tomoco95** [comment]
#34
