### ISSUE TITLE
Webロゴ掲載(日本インサイトテクノロジー株式会社さま)

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2023.scalamatsuri.org#43]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する
template:
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: “http://www.insightech.co.jp/”
}
ロゴ画像:https://drive.google.com/file/d/1zpe5dXcSgGGNtop6WX5tvSPdc4d1vbr4/view?usp=sharing

**Comment by tomoco95** [comment]
#44
