### ISSUE TITLE
Webロゴ掲載(ScalaTimesさま)

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2023.scalamatsuri.org#50]
- [ ] リポジトリにロゴを入れる
- [ ] jsonファイルを変更する
- [ ] develop branchに向けてPullRequestを送る
- [ ] staging環境で表示を確認する
- [ ] developからmaster branchに向けてPullRequestを送る
- [ ] merge後、production環境のWebサイトに反映されていることを確認する
template:
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: “https://scalatimes.com/”
}
ロゴ画像:https://drive.google.com/file/d/1JfPfqtXkmR7ahOnpyvaPFbsogG-JK1e8/view?usp=sharing

**Comment by Iwaji** [comment]
"Bugyo Sponsor"です。
ご参考：今までのやり取りhttps://github.com/scalajp/2023.staff/issues/66

**Comment by tomoco95** [comment]
ロゴを20*7にサイズ調整しました
https://drive.google.com/file/d/1TIqX9sKPT6DVvZU1TwYdp__F-m8ALZmE/view?usp=sharing

**Comment by tomoco95** [comment]
ロゴ掲載し、先方へのご連絡も完了しました！
