### ISSUE TITLE
Harrasment Incident Report Form Expired

### ISSUE THREAD

**Issue by zmccoy** [scalamatsuri/2023.scalamatsuri.org#80]
This link form https://docs.google.com/forms/d/e/1FAIpQLSesyF_I6jU-78gV0bEERDIpBzwiw1WFSBMxYk73he-NYcP8Xw/closedform links to a form that's no longer accepted.  

This is linked to from this page: https://scalamatsuri.org/en/code-of-conduct

**Comment by eed3si9n** [comment]
Hi Zach, thanks for the report. Currently we turn on the report form only during the conference, I think to prevent the situation where no one is monitoring the reports. During the conference I think it gets hooked up to a Slack channel, and hopefully we can bring it back up soon for this year.

**Comment by zmccoy** [comment]
Perfect that sounds great!  Thank you.
